# Generated by Django 4.2.7 on 2025-10-10 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Collector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "collector_organization",
                    models.CharField(max_length=200, verbose_name="采集者组织"),
                ),
                (
                    "collector_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="采集者ID"
                    ),
                ),
                (
                    "collector_name",
                    models.CharField(max_length=100, verbose_name="采集者姓名"),
                ),
                (
                    "target_customer",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="目标客户"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "采集者",
                "verbose_name_plural": "采集者",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "episode_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Episode ID"
                    ),
                ),
                (
                    "task_name",
                    models.CharField(max_length=200, verbose_name="任务名称"),
                ),
                (
                    "init_scene_text",
                    models.TextField(
                        blank=True, null=True, verbose_name="初始场景文本"
                    ),
                ),
                (
                    "action_config",
                    models.JSONField(default=list, verbose_name="动作配置"),
                ),
                (
                    "observations_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="观察数据ID"
                    ),
                ),
                (
                    "parameters_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="参数数据ID"
                    ),
                ),
                (
                    "skeletonData_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="骨骼数据ID"
                    ),
                ),
                (
                    "kinematicData_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="运动学数据ID"
                    ),
                ),
                (
                    "imu_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="IMU数据ID"
                    ),
                ),
                (
                    "tactile_feedback_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="触觉反馈数据ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "collector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_collection.collector",
                        verbose_name="采集者",
                    ),
                ),
            ],
            options={
                "verbose_name": "任务信息",
                "verbose_name_plural": "任务信息",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TactileFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "episode_id",
                    models.CharField(max_length=100, verbose_name="Episode ID"),
                ),
                (
                    "leftHandTac_path",
                    models.CharField(max_length=500, verbose_name="左手触觉路径"),
                ),
                (
                    "rightHandTac_path",
                    models.CharField(max_length=500, verbose_name="右手触觉路径"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "task_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_collection.taskinfo",
                        verbose_name="任务信息",
                    ),
                ),
            ],
            options={
                "verbose_name": "触觉反馈数据",
                "verbose_name_plural": "触觉反馈数据",
            },
        ),
        migrations.CreateModel(
            name="SkeletonData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "episode_id",
                    models.CharField(max_length=100, verbose_name="Episode ID"),
                ),
                (
                    "fbx_path",
                    models.CharField(max_length=500, verbose_name="FBX文件路径"),
                ),
                (
                    "bvh_path",
                    models.CharField(max_length=500, verbose_name="BVH文件路径"),
                ),
                (
                    "csv_path",
                    models.CharField(max_length=500, verbose_name="CSV文件路径"),
                ),
                (
                    "npy_path",
                    models.CharField(max_length=500, verbose_name="NPY文件路径"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "task_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_collection.taskinfo",
                        verbose_name="任务信息",
                    ),
                ),
            ],
            options={
                "verbose_name": "骨骼数据",
                "verbose_name_plural": "骨骼数据",
            },
        ),
        migrations.CreateModel(
            name="Parameters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "episode_id",
                    models.CharField(max_length=100, verbose_name="Episode ID"),
                ),
                (
                    "parameters_path",
                    models.CharField(max_length=500, verbose_name="参数文件路径"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "task_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_collection.taskinfo",
                        verbose_name="任务信息",
                    ),
                ),
            ],
            options={
                "verbose_name": "参数数据",
                "verbose_name_plural": "参数数据",
            },
        ),
        migrations.CreateModel(
            name="Observations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "episode_id",
                    models.CharField(max_length=100, verbose_name="Episode ID"),
                ),
                (
                    "video_path",
                    models.CharField(max_length=500, verbose_name="视频路径"),
                ),
                (
                    "depth_path",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="深度图路径"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "task_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_collection.taskinfo",
                        verbose_name="任务信息",
                    ),
                ),
            ],
            options={
                "verbose_name": "观察数据",
                "verbose_name_plural": "观察数据",
            },
        ),
        migrations.CreateModel(
            name="KinematicData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "episode_id",
                    models.CharField(max_length=100, verbose_name="Episode ID"),
                ),
                ("path", models.CharField(max_length=500, verbose_name="数据文件路径")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "task_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_collection.taskinfo",
                        verbose_name="任务信息",
                    ),
                ),
            ],
            options={
                "verbose_name": "运动学数据",
                "verbose_name_plural": "运动学数据",
            },
        ),
        migrations.CreateModel(
            name="IMUData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "episode_id",
                    models.CharField(max_length=100, verbose_name="Episode ID"),
                ),
                (
                    "leftHandIMU_path",
                    models.CharField(max_length=500, verbose_name="左手IMU路径"),
                ),
                (
                    "rightHandIMU_path",
                    models.CharField(max_length=500, verbose_name="右手IMU路径"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "task_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_collection.taskinfo",
                        verbose_name="任务信息",
                    ),
                ),
            ],
            options={
                "verbose_name": "IMU数据",
                "verbose_name_plural": "IMU数据",
            },
        ),
    ]
