# Generated by Django 4.2.7 on 2025-10-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_collection", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskinfo",
            name="task_status",
            field=models.CharField(
                choices=[
                    ("pending", "待审核"),
                    ("accepted", "已接受"),
                    ("rejected", "已拒绝"),
                    ("ng", "NG"),
                ],
                default="pending",
                max_length=20,
                verbose_name="任务状态",
            ),
        ),
    ]
