# Generated by Django 4.2.7 on 2025-10-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_collection", "0002_taskinfo_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskinfo",
            name="task_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=100,
                verbose_name="任务ID",
            ),
        ),
    ]
