# Generated by Django 4.2 on 2025-10-11 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_collection", "0003_taskinfo_task_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="observations",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "观察数据",
                "verbose_name_plural": "观察数据",
            },
        ),
    ]
