# Generated by Django 4.2.7 on 2025-10-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_collection", "0004_alter_observations_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="collector",
            name="password",
            field=models.CharField(default="", max_length=100, verbose_name="密码"),
        ),
        migrations.AddField(
            model_name="collector",
            name="username",
            field=models.CharField(
                default="", max_length=100, unique=True, verbose_name="用户名"
            ),
        ),
    ]
