# Generated by Django 4.2.7 on 2025-10-16 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("data_collection", "0005_collector_password_collector_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskinfo",
            name="objectData_id",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="物体模型数据ID"
            ),
        ),
        migrations.CreateModel(
            name="ObjectData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "episode_id",
                    models.CharField(max_length=100, verbose_name="Episode ID"),
                ),
                (
                    "fbx_path",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="FBX文件路径",
                    ),
                ),
                (
                    "cmb_path",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="CMB文件路径",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "task_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_collection.taskinfo",
                        verbose_name="任务信息",
                    ),
                ),
            ],
            options={
                "verbose_name": "物体模型数据",
                "verbose_name_plural": "物体模型数据",
            },
        ),
    ]
