# Generated by Django 4.2.7 on 2025-10-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_collection", "0006_taskinfo_objectdata_id_objectdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskinfo",
            name="recording_end_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="录制结束时间"
            ),
        ),
        migrations.AddField(
            model_name="taskinfo",
            name="task_name_cn",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="任务中文名称"
            ),
        ),
    ]
