# Generated by Django 4.2.7 on 2025-10-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_collection", "0007_taskinfo_recording_end_time_taskinfo_task_name_cn"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskinfo",
            name="exported",
            field=models.BooleanField(default=False, verbose_name="是否已导出"),
        ),
    ]
